vim.keymap.set('n', '<F5>', function()
  local filename = vim.fn.shellescape(vim.fn.expand '%')
  vim.cmd.split(string.format("term://python %s", filename))
  vim.cmd.startinsert()
end, { buffer = true })
