alias ytdl-audio='youtube-dl --extract-audio'
alias matlab-cli='matlab -nosplash -nodesktop'
alias mpv='mpv --no-audio-display'
alias tlmgr='tlmgr --verify-repo=none --no-persistent-downloads'
alias latexmk='latexmk -pdf -halt-on-error'
alias rsync='rsync --archive --verbose --human-readable --progress'
alias cp='cp --verbose --interactive'
alias mv='mv --verbose --interactive'
alias rm='rm --verbose --interactive'
alias rg='rg --smart-case'
alias R='R --no-restore --no-save --quiet'
alias dotfiles='git --git-dir=$HOME/.dotfiles.git --work-tree=$HOME'
alias numpy='python -i -c "import numpy as np; import matplotlib.pyplot as plt"'

lf () { cd "$(command lf -print-last-dir "$@")"; }
