#!/usr/bin/env python

import os, subprocess
from itertools import chain

exts = [
    'aux',
    'bbl',
    'blg',
    'fdb_latexmk',
    'fls',
    'log',
    'nav',
    'out',
    'snm',
    'synctex(busy)',
    'synctex.gz',
    'toc',
    'xdv',
    'lot',
    'lof',
]

def auxfiles(file):
    base, ext = file[:-4], file[-4:]
    if ext == '.tex': return [base + '.' + ext for ext in exts]
    if ext == '.eps': return [base + '-eps-converted-to.pdf']
    return []

files = set(os.listdir())
if files_to_remove := [f for f in chain(*map(auxfiles, files)) if f in files]:
    subprocess.run(['trash', *files_to_remove])
