#!/usr/bin/env python

from sys import argv
from subprocess import run

if len(argv) > 1 and argv[1] == '--reset':
    run(['dconf', 'reset', '-f', '/org/mate/terminal/'])
    exit()

palette = [ # kanagawa: https://github.com/rebelot/kanagawa.nvim
    '#090618', '#c34043', '#76946a', '#c0a36e',
    '#7e9cd8', '#957fb8', '#6a9589', '#c8c093',
    '#727169', '#e82424', '#98bb6c', '#e6c384',
    '#7fb4ca', '#938aa9', '#7aa89f', '#dcd7ba',
]
background = '#1f1f28'
foreground = '#dcd7ba'

stdin = f"""
    [profiles/default]
    visible-name='Default'
    copy-selection=true
    use-system-font=false
    use-theme-colors=false
    scrollbar-position='hidden'
    default-show-menubar=false
    font='Fira Code Regular 12'
    allow-bold=true
    palette='{":".join(palette)}'
    background-color='{background}'
    foreground-color='{foreground}'
    bold-color='{foreground}'
"""

run(['dconf', 'load', '/org/mate/terminal/'], text=True, input=stdin)
