#!/usr/bin/env bash

read -d '' file < <(
  fzf --delimiter='/' --nth=-1 --with-nth=-1 \
    --bind=ctrl-y:accept --reverse --no-info \
    --preview='pdftotext -l 5 {} -' \
    --query="$*" --select-1 --print0 \
    < <(locate '*.pdf')
  )
if [[ -n $file ]]; then
  echo "$file"
  xdg-open "$file" 2>/dev/null &
fi
