#!/usr/bin/env python

import sys, re

ndigits = int(sys.argv[1]) if len(sys.argv) > 1 else 3

pattern = re.compile(r"[-+]?[0-9]*\.?[0-9]+([eE][-+]?[0-9]+)?")
repl = lambda m: f"{float(m.group(0)):.{ndigits}f}"

for line in sys.stdin:
    print(pattern.sub(repl, line), end="")
