#!/usr/bin/env bash
# print temperature and memory usage; perhaps useful for desktop panel

# temperature
sensors -u | awk '
BEGIN              { temp = 0 }
/temp[0-9]*_input/ { temp = ($2 > temp) ? $2 : temp }
END                { printf "%.1f°C  ", temp }
'

# memory usage
free -m | awk '
/^Mem:/ {
  used = $3 + $5; free = $2
  used = (used >= 1000) ? sprintf("%.2fG", used / 1000) : sprintf("%dM", used)
  free = sprintf("%.2fG", free / 1000)
  print used "/" free
}
'
